apiVersion: forma.dev/v1alpha1
kind: Config
metadata:
  name: app
  description: Konfigurasi aplikasi CRC
spec:
  keys:
    crc.wo_prefix:
      type: string
      default: "WO"
    crc.cl_prefix:
      type: string
      default: "CL"
    crc.sr_prefix:
      type: string
      default: "SR"
    crc.pr_prefix:
      type: string
      default: "PR"
