apiVersion: forma.dev/v1alpha1
kind: Page
metadata:
  name: service-report-list
  module: crc
  description: Halaman daftar Service Report
spec:
  route: /service-reports
  title: "Service Report"
  icon: "file-bar-chart"
  permissions: [service-report.view]
  blocks:
    - table:
        ref: service-report-list
