apiVersion: forma.dev/v1alpha1
kind: Entity
metadata:
  name: address
  module: billing
  description: Alamat pelanggan — billing, shipping, dll.
spec:
  version: v1
  characteristic: master

  fields:
    - name: customer_id
      type: relation
      relation: { type: belongs_to, resource: customer }
      immutable: true
    - name: type
      type: enum
      enum_values: [billing, shipping, both]
      default: shipping
    - name: label
      type: string
      description: Nama label alamat — "Rumah", "Kantor"
    - name: street
      type: string
      rules: [required]
    - name: city
      type: string
      rules: [required]
    - name: postal_code
      type: string
    - name: is_default
      type: boolean
      default: false
