apiVersion: formspec.dev/v1alpha1
kind: Entity
metadata:
  name: chemical
  module: crc-master
  description: "Master bahan kimia (Chemical)"
spec:
  version: v1
  characteristic: master
  display_field: chemical_name
  fields:
    - name: chemical_name
      type: string
      required: true
      title: "Nama Kimia"
    - name: chemical_serial_no
      type: string
      title: "Chemical Serial No"
    - name: msds_no
      type: string
      title: "MSDS No"
  soft_deactivate:
    enabled: true
  expose:
    - type: rest
      actions: [list, find, create, update]
