package formspec

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/primadi/formspec/internal/api"
	"github.com/primadi/formspec/internal/auth"
)

// TestUserPasswordHashHook verifies that creating a user via the entity API
// with a plaintext `password` field hashes it into `password_hash` (the
// before-create native hook), never stores plaintext, and the resulting user
// can log in.
func TestUserPasswordHashHook(t *testing.T) {
	dir := t.TempDir()
	buildAuthSpecDir(t, dir)
	api.ResetAuthRateLimiters()

	app, err := New(Config{
		SpecPath:  dir,
		DSN:       "sqlite:" + filepath.Join(t.TempDir(), "user_hash.db"),
		JWTSecret: "test-secret",
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	defer app.Close(context.Background())

	// Auth is uniform across dev and prod — no auto-seeding. Create the
	// first admin the way production does (or via direct insert, as here).
	seedUser(t, app, "admin", "admin", []string{"*"})

	adminTok := login(t, app, "admin", "admin")

	// Create a user with a plaintext password via the entity API.
	status, out := doAuthed(t, app, "POST", "/default/_ui/entity/formspec.core/user", adminTok, map[string]any{
		"username":     "alice",
		"password":     "secret123",
		"display_name": "Alice",
		"active":       true,
	})
	if status != 201 {
		t.Fatalf("create user: status %d, body %v", status, out)
	}
	rec, _ := out["data"].(map[string]any)
	if rec == nil {
		t.Fatalf("create user: no record in response: %v", out)
	}
	if _, hasPw := rec["password"]; hasPw {
		t.Fatalf("plaintext password leaked into stored record")
	}
	// password_hash is masked in the response but must be present (non-empty).
	hash, _ := rec["password_hash"].(string)
	if hash == "" {
		t.Fatalf("expected password_hash in stored record")
	}

	// The new user can log in with the plaintext password.
	aliceTok := login(t, app, "alice", "secret123")
	if aliceTok == "" {
		t.Fatal("expected alice login to succeed")
	}
}

// TestAuth_ValidatorSelection verifies that auth is uniform across dev and
// prod: configureAuth always installs a JWTValidator, and a missing secret
// is auto-generated by New() so issued tokens validate against the
// middleware. The old DevValidator bypass is gone.
func TestAuth_ValidatorSelection(t *testing.T) {
	// Explicit secret → JWTValidator.
	api.SetAuthValidator(nil)
	if err := configureAuth(Config{JWTSecret: "test-secret"}); err != nil {
		t.Fatalf("configureAuth: %v", err)
	}
	if _, ok := api.GetAuthValidator().(*auth.JWTValidator); !ok {
		t.Fatalf("expected JWTValidator, got %T", api.GetAuthValidator())
	}

	// No secret and no public key → configureAuth errors (prod gate); New()
	// auto-generates a dev secret before calling it.
	api.SetAuthValidator(nil)
	if err := configureAuth(Config{}); err == nil {
		t.Fatal("expected error for configureAuth without secret/public key")
	}

	// New() without a secret → auto-generated, still JWTValidator.
	dir := t.TempDir()
	buildAuthSpecDir(t, dir)
	app, err := New(Config{
		SpecPath: dir,
		DSN:      "sqlite:" + filepath.Join(t.TempDir(), "dev_auth.db"),
	})
	if err != nil {
		t.Fatalf("New(dev): %v", err)
	}
	defer app.Close(context.Background())
	if _, ok := api.GetAuthValidator().(*auth.JWTValidator); !ok {
		t.Fatalf("expected JWTValidator after New(dev), got %T", api.GetAuthValidator())
	}
}

// TestAuth_LoginFlow verifies the full auth flow (uniform across dev and
// prod): an anonymous request resolves to the "anonymous" identity (no
// permissions), the first admin can log in, and the issued token
// authenticates subsequent requests as the real user.
func TestAuth_LoginFlow(t *testing.T) {
	dir := t.TempDir()
	buildAuthSpecDir(t, dir)
	api.ResetAuthRateLimiters()

	app, err := New(Config{
		SpecPath:  dir,
		DSN:       "sqlite:" + filepath.Join(t.TempDir(), "dev_auth_flow.db"),
		JWTSecret: "test-secret",
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	defer app.Close(context.Background())

	// No auto-seeding — create the first admin via the setup endpoint,
	// exactly like the first-run wizard does.
	if status, out := doJSON(t, app, "POST", "/default/_ui/setup", map[string]any{
		"username": "admin", "password": "admin12345", "display_name": "Admin",
	}); status != 201 {
		t.Fatalf("setup first admin: status %d, body %v", status, out)
	}

	// Anonymous → identity is "anonymous" with no permissions (auth enforced,
	// unlike plain dev mode which returns the synthetic developer identity).
	status, out := doJSON(t, app, "GET", "/default/_ui/_meta/me", nil)
	if status != 200 {
		t.Fatalf("expected 200 for anonymous _meta/me, got %d", status)
	}
	data, _ := out["data"].(map[string]any)
	if uid, _ := data["user_id"].(string); uid != "anonymous" {
		t.Fatalf("expected anonymous identity, got user_id=%q", uid)
	}

	// First admin (created via setup) logs in.
	adminTok := login(t, app, "admin", "admin12345")

	// Authenticated → identity is the real user (internal user UUID, not the
	// "anonymous" sentinel).
	status, out = doAuthed(t, app, "GET", "/default/_ui/_meta/me", adminTok, nil)
	if status != 200 {
		t.Fatalf("expected 200 for authed _meta/me, got %d (body %v)", status, out)
	}
	data, _ = out["data"].(map[string]any)
	if uid, _ := data["user_id"].(string); uid == "" || uid == "anonymous" {
		t.Fatalf("expected a real user identity, got user_id=%q", uid)
	}
}
