package formspec

import (
	"context"
	"testing"

	"github.com/primadi/formspec/pkg/spec"
	db "github.com/primadi/formspec/renderers/jsonb-persist"
)

// TestKafe_AutoGeneratedKeysIgnoreCallerValues pins the `natural_key_entry:
// auto_generated` contract on the real kafe entities whose key the UI never
// offers as an input: `order.number` (locked `read_only` in the POS form) and
// `purchase-order.number` (absent from `purchase-order-form` entirely).
//
// In both cases the literal is a caller value that must be DISCARDED, because
// accepting it would let a caller pin a number the sequence later hands to a
// different record. That is the difference from `auto_generated_if_empty`: under
// the previous mode the supplied number would have won.
//
// It writes through the registry's store rather than HTTP on purpose: the shared
// test user lives in the `default` workspace (`seedUser`), so an HTTP call to the
// `kafe` surface would be scoped to the wrong tenant.
func TestKafe_AutoGeneratedKeysIgnoreCallerValues(t *testing.T) {
	app := bootKafe(t)

	// The branch both scoped sequences key off. The relation stores the branch's
	// ID (not its `code`).
	branchStore, err := app.GetEntityStore("cafe-master", "branch")
	if err != nil {
		t.Fatalf("GetEntityStore(cafe-master/branch): %v", err)
	}
	branchID, err := branchStore.Insert(context.Background(), db.InsertParams{
		WorkspaceID: "kafe", CreatedBy: "test",
		Data: map[string]any{"code": "KFE-JKT-01", "name": "Cabang Jakarta"},
	})
	if err != nil {
		t.Fatalf("seed branch: %v", err)
	}

	supplierStore, err := app.GetEntityStore("cafe-stock", "supplier")
	if err != nil {
		t.Fatalf("GetEntityStore(cafe-stock/supplier): %v", err)
	}
	supplierID, err := supplierStore.Insert(context.Background(), db.InsertParams{
		WorkspaceID: "kafe", CreatedBy: "test",
		Data: map[string]any{"code": "SUP-ENTRY", "name": "Pemasok Entry Mode"},
	})
	if err != nil {
		t.Fatalf("seed supplier: %v", err)
	}

	cases := []struct {
		name    string
		module  string
		entity  string
		keyName string
		payload map[string]any
	}{
		{
			name: "order.number", module: "cafe-order", entity: "order", keyName: "number",
			payload: map[string]any{
				"transaction_date": recentDate(),
				"branch_id":        branchID,
			},
		},
		{
			name: "purchase-order.number", module: "cafe-stock", entity: "purchase-order", keyName: "number",
			payload: map[string]any{
				"transaction_date": recentDate(),
				"branch_id":        branchID,
				"supplier_id":      supplierID,
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Assert the declaration first, so the test fails if the manifest
			// drifts even when the behaviour happens to look right.
			info, ok := app.Registry().GetEntity(tc.module, tc.entity)
			if !ok || info.EntitySpec == nil {
				t.Fatalf("%s/%s is not registered", tc.module, tc.entity)
			}
			var key *spec.Field
			for i := range info.EntitySpec.Fields {
				if info.EntitySpec.Fields[i].Name == tc.keyName {
					key = &info.EntitySpec.Fields[i]
					break
				}
			}
			if key == nil {
				t.Fatalf("%s has no %q field", tc.entity, tc.keyName)
			}
			if got := spec.ResolveNaturalKeyEntry(key); got != spec.NaturalKeyEntryAutoGenerated {
				t.Fatalf("entry mode = %q, want %q", got, spec.NaturalKeyEntryAutoGenerated)
			}
			if !spec.HasNaturalKeyGenerator(key) {
				t.Error("auto_generated needs a generator, and none was declared")
			}

			store, err := app.GetEntityStore(tc.module, tc.entity)
			if err != nil {
				t.Fatalf("GetEntityStore(%s/%s): %v", tc.module, tc.entity, err)
			}

			const pinned = "CALLER-TRIED-TO-PIN-THIS"
			data := map[string]any{tc.keyName: pinned}
			for k, v := range tc.payload {
				data[k] = v
			}
			id, err := store.Insert(context.Background(), db.InsertParams{
				WorkspaceID: "kafe", CreatedBy: "test", Data: data,
			})
			if err != nil {
				t.Fatalf("insert: %v", err)
			}
			rec, err := store.GetByID(context.Background(), db.GetByIDParams{
				WorkspaceID: "kafe", ID: id,
			})
			if err != nil || rec == nil {
				t.Fatalf("GetByID(%s): %v", id, err)
			}
			got, _ := rec.Data[tc.keyName].(string)
			if got == pinned {
				t.Errorf("auto_generated must ignore a caller-supplied key, got %q", got)
			}
			if got == "" {
				t.Error("expected the engine to mint a key, got an empty one")
			}
		})
	}
}
