// Command `forma generate node-app` scaffolds a TypeScript sidecar app for a
// new Forma project. It creates the complete boilerplate: package.json,
// tsconfig, entrypoint with App listener, example handler, and a
// forma-sidecar.yaml that enables `forma dev --runtime node` with tsx watch.
//
// Usage:
//
//	forma generate node-app [--dir ./my-app] [--module my-module] [--entity my-entity]
//
// Flags:
//
//	--dir        Target directory (default: ./app)
//	--module     Module name for example handler (default: "myapp")
//	--entity     Entity name for example handler (default: "myentity")
//	--action     Action name for example handler (default: "process")
package main

import (
	_ "embed"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runGenerateNodeApp scaffolds a new Node.js TypeScript sidecar app.
func runGenerateNodeApp(args []string) {
	fs := flag.NewFlagSet("generate node-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate node-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a TypeScript sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	// Check target directory doesn't already exist
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	// Create directory structure
	dirs := []string{
		filepath.Join(absDir, "src", "handlers"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create %s: %v\n", d, err)
			os.Exit(1)
		}
	}

	// Write files
	files := map[string]string{
		"package.json":  scaffoldPackageJSON(),
		"tsconfig.json": scaffoldTSConfig(),
		"src/app.ts":    scaffoldAppTS(mod, ent, act),
		filepath.Join("src", "handlers", act+".ts"): scaffoldHandlerTS(mod, ent, act),
		"forma-sidecar.yaml":                        scaffoldFormaSidecarYAML(),
		".gitignore":                                scaffoldGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Node.js sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  npm install\n")
	fmt.Printf("  cd .. && forma dev\n")
	fmt.Printf("\nEdit src/handlers/%s.ts to implement your business logic.\n", act)
	fmt.Printf("The entrypoint %s.%s.%s will be served via sidecar.\n", mod, ent, act)
}

func scaffoldPackageJSON() string {
	return `{
  "name": "my-forma-app",
  "version": "0.1.0",
  "private": true,
  "description": "Forma TypeScript sidecar app",
  "type": "commonjs",
  "dependencies": {
    "@forma/lib-forma": "file:../../sdk/typescript"
  },
  "devDependencies": {
    "typescript": "^5.5.0",
    "@types/node": "^20.14.0",
    "tsx": "^4.19.0"
  },
  "scripts": {
    "build": "tsc",
    "dev": "tsx --watch src/app.ts",
    "start": "node dist/app.js"
  }
}
`
}

func scaffoldTSConfig() string {
	return `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "types": ["node"],
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "declaration": false,
    "sourceMap": false
  },
  "include": ["src/**/*"]
}
`
}

func scaffoldAppTS(module, entity, action string) string {
	return fmt.Sprintf(`/**
 * Forma TypeScript sidecar app — generated by `+"`forma generate node-app`"+`.
 *
 * Registers business-logic handlers and starts the App listener on
 * FORMA_APP_SOCKET (unix:///tmp/forma-app.sock by default).
 *
 * forma dev spawns this process as a child, calls POST /invoke/... for
 * actions with impl: { type: sidecar }, and forwards ctx.* primitive
 * calls back to the engine over FORMA_SIDECAR_SOCKET.
 */

import { App } from "@forma/lib-forma";
import { register%sHandler } from "./handlers/%s";

const app = new App();
register%sHandler(app);

app.run().then((server) => {
  const addr = server.address();
  process.stderr.write("[%s] ready on " + JSON.stringify(addr) + "\n");
});
`, pascalCase(module)+pascalCase(entity), action, pascalCase(module)+pascalCase(entity), module)
}

func scaffoldHandlerTS(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	handlerType := pascalCase(module) + pascalCase(entity)

	return fmt.Sprintf(`/**
 * %s handler — example sidecar action.
 *
 * This runs in a Node.js child process, communicating with the forma engine
 * over a unix domain socket. Use ctx.entity() for atomic entity operations.
 *
 * Register this handler in src/app.ts.
 */

import { ActionResult, App } from "@forma/lib-forma";

export function register%sHandler(app: App): void {
  app.handle("%s", async (inv, ctx) => {
    process.stderr.write("[%s] invoked: resource_id=" + inv.resourceId + "\n");

    // Example: use ctx.entity() for atomic field operations.
    //   await ctx
    //     .entity()
    //     .named("module/entity")
    //     .decrement(inv.resourceId, "stock", 1, inv.tenantId);

    // Return action result with optional state transition.
    return new ActionResult(
      { processed: true, at: new Date().toISOString() },
      "processed",
    );
  });
}
`, pascalCase(module)+pascalCase(entity)+pascalCase(action), handlerType, handlerID, handlerID)
}

func scaffoldFormaSidecarYAML() string {
	return `# ── Forma Dev Config — TypeScript Sidecar App ──
#
# Generated by ` + "`forma generate node-app`" + `.
# Run ` + "`forma dev`" + ` from this directory to start the dev server.
#
# The entrypoint is .ts so forma uses tsx --watch (auto-reload on change).

spec: spec
dsn: sqlite:.forma/data.db
runtime: node
app-dir: app
app-entrypoint: src/app.ts
listen: unix_socket
app-endpoint: unix_socket
listen-url: unix:///tmp/forma-sidecar.sock
app-endpoint-url: unix:///tmp/forma-app.sock
dev: true
`
}

func scaffoldGitignore() string {
	return `node_modules/
dist/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
