// Command `forma generate dotnet-app` scaffolds a .NET sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGenerateDotNetApp(args []string) {
	fs := flag.NewFlagSet("generate dotnet-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate dotnet-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a .NET sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	files := map[string]string{
		"App.csproj":     scaffoldDotNetCSProj(),
		"Program.cs":     scaffoldDotNetProgram(mod, ent, act),
		"forma-app.yaml": scaffoldDotNetAppYAML(),
		".gitignore":     scaffoldDotNetGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded .NET sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldDotNetCSProj() string {
	return `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../sdk/dotnet/src/FormaLib/FormaLib.csproj" />
  </ItemGroup>

</Project>
`
}

func scaffoldDotNetProgram(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return `using Forma;

// Forma .NET sidecar app -- generated by ` + "`forma generate dotnet-app`" + `.

var app = new App();

app.Handle("` + handlerID + `", async (Invocation inv, Ctx ctx) =>
{
    Console.Error.WriteLine($"` + "[" + handlerID + `] invoked: resource_id={inv.ResourceId}");
    return new ActionResult(
        new { processed = true, at = DateTime.UtcNow.ToString("O") },
        "processed"
    );
});

await app.RunAsync();
`
}

func scaffoldDotNetAppYAML() string {
	return `# ── Forma App Config — .NET Sidecar App ──
#
# Generated by ` + "`forma generate dotnet-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: dotnet
app-dir: app
app-entrypoint: Program.cs
dev: true
`
}

func scaffoldDotNetGitignore() string {
	return `bin/
obj/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
