// Command `forma generate rust-app` scaffolds a Rust sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGenerateRustApp(args []string) {
	fs := flag.NewFlagSet("generate rust-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate rust-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a Rust sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	dirs := []string{
		filepath.Join(absDir, "src"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create %s: %v\n", d, err)
			os.Exit(1)
		}
	}

	files := map[string]string{
		"Cargo.toml":     scaffoldRustCargo(mod),
		"src/main.rs":    scaffoldRustMain(mod, ent, act),
		"forma-app.yaml": scaffoldRustAppYAML(),
		".gitignore":     scaffoldRustGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Rust sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldRustCargo(module string) string {
	return fmt.Sprintf(`[package]
name = "%s"
version = "0.1.0"
edition = "2021"
description = "Forma Rust sidecar app"

[dependencies]
lib-forma = { path = "../../sdk/rust" }
`, module)
}

func scaffoldRustMain(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return fmt.Sprintf(`// Forma Rust sidecar app — generated by `+"`forma generate rust-app`"+`.
//
// Registers business-logic handlers and starts the App listener.

use lib_forma::{App, ActionResult};

fn main() {
    let mut app = App::new();

    app.handle("%s", |inv, _ctx| {
        eprintln!("[%s] invoked: resource_id={}", inv.resource_id);
        ActionResult {
            data: serde_json::json!({
                "processed": true,
                "at": chrono::Utc::now().to_rfc3339(),
            }),
            new_state: Some("processed".to_string()),
        }
    });

    app.run();
}
`, handlerID, handlerID)
}

func scaffoldRustAppYAML() string {
	return `# ── Forma App Config — Rust Sidecar App ──
#
# Generated by ` + "`forma generate rust-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: rust
app-dir: app
dev: true
`
}

func scaffoldRustGitignore() string {
	return `target/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
