// Command `forma generate go-app` scaffolds a Go sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGenerateGoApp(args []string) {
	fs := flag.NewFlagSet("generate go-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate go-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a Go sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	files := map[string]string{
		"go.mod":         scaffoldGoMod(mod),
		"main.go":        scaffoldGoMain(mod, ent),
		"handler.go":     scaffoldGoHandler(mod, ent, act),
		"forma-app.yaml": scaffoldGoAppYAML(),
		".gitignore":     scaffoldGoGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Go sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldGoMod(module string) string {
	return fmt.Sprintf(`module %s

go 1.26

require github.com/primadi/forma/sdk/go v0.1.0

replace github.com/primadi/forma/sdk/go => ../../sdk/go
`, module)
}

func scaffoldGoMain(module, entity string) string {
	return fmt.Sprintf(`package main

import (
	"encoding/json"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
)

func main() {
	socketPath := os.Getenv("FORMA_APP_SOCKET")
	if socketPath == "" {
		socketPath = "/tmp/forma-app.sock"
	}
	socketPath = strings.TrimPrefix(socketPath, "unix://")

	// Remove old socket file
	os.Remove(socketPath)

	mux := http.NewServeMux()
	register%s%sHandler(mux)

	listener, err := net.Listen("unix", socketPath)
	if err != nil {
		log.Fatalf("listen %%s: %%v", socketPath, err)
	}
	log.Printf("[%s] ready on %%s", socketPath)
	if err := http.Serve(listener, mux); err != nil {
		log.Fatalf("serve: %%v", err)
	}
}
`, pascalCase(module), pascalCase(entity), module)
}

func scaffoldGoHandler(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	route := fmt.Sprintf("/invoke/%s/%s/%s", module, entity, action)
	return fmt.Sprintf(`package main

import (
	"encoding/json"
	"log"
	"net/http"
)

// register%[1]s%[2]s%[3]sHandler registers the %[4]s handler on route %[5]s.
func register%[1]s%[2]s%[3]sHandler(mux *http.ServeMux) {
	mux.HandleFunc("%[5]s", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("[%[4]s] invoked")

		resp := map[string]interface{}{
			"data": map[string]interface{}{
				"processed": true,
				"at":        "", // timestamp placeholder
			},
			"new_state": "processed",
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	})
}
`, pascalCase(module), pascalCase(entity), pascalCase(action), handlerID, route)
}

func scaffoldGoAppYAML() string {
	return `# ── Forma App Config — Go Sidecar App ──
#
# Generated by ` + "`forma generate go-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: go
app-dir: app
dev: true
`
}

func scaffoldGoGitignore() string {
	return `.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
app/
`
}
