// Command `forma generate` derives a typed TypeScript client from loaded
// entity manifests — the codegen half of `forma.api` (docs/spec/05-frontend.md
// §7; docs/spec/02-core-basic.md §16, §23). The hand-written runtime half
// (auth, HTTP, error mapping) lives in the published package @forma/client
// (sdk/browser) — this command only emits per-entity types and a thin typed
// wrapper on top of it.
//
// Usage:
//
//	forma generate --spec ./spec --out ./src/generated/forma-client.ts
//
// Only --lang typescript is implemented today; Go types and OpenAPI export
// (docs/cli-tools/01-forma-cli.md §5) are speced but not built.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/primadi/forma/internal/api"
	"github.com/primadi/forma/internal/db"
	"github.com/primadi/forma/internal/entity"
	"github.com/primadi/forma/pkg/spec"
)

func runGenerate(args []string) {
	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	specPath := fs.String("spec", "./spec", "Manifest directory to generate from")
	lang := fs.String("lang", "typescript", "Target language(s), comma-separated")
	out := fs.String("out", "./forma-client.generated.ts", "Output file path")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Derive a typed TypeScript client from entity manifests.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	for _, l := range strings.Split(*lang, ",") {
		if strings.TrimSpace(l) != "typescript" {
			fmt.Fprintf(os.Stderr, "forma generate: unsupported --lang %q — only \"typescript\" is implemented today (Go/OpenAPI are speced in docs/cli-tools/01-forma-cli.md §5 but not built)\n", l)
			os.Exit(1)
		}
	}

	reg, err := loadRegistryForCodegen(*specPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	ts, err := generateTypeScript(reg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error: create output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(ts), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", *out, err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated %s\n", *out)
}

// loadRegistryForCodegen loads entity manifests without touching a real
// database — codegen only reads spec.EntitySpec, it never syncs schema or
// runs queries, so an in-memory SQLite handle exists purely to satisfy
// entity.NewRegistry's constructor.
func loadRegistryForCodegen(specPath string) (*entity.Registry, error) {
	database, err := db.Open("sqlite::memory:")
	if err != nil {
		return nil, fmt.Errorf("open in-memory db: %w", err)
	}

	reg := entity.NewRegistry(database, db.DriverSQLite, specPath)
	for _, loadErr := range reg.LoadEntities() {
		fmt.Fprintf(os.Stderr, "forma generate: load warning: %v\n", loadErr)
	}
	return reg, nil
}

// entityGroup collects the generated routes for one entity, keyed by
// module+entity — the same grouping RouteDescriptor already encodes, reused
// here instead of re-deriving expose/pluralization/disabled-action rules
// (internal/api/generator.go is the single source of truth for those).
type entityGroup struct {
	module, entity, plural string
	spec                   *spec.EntitySpec
	standardActions        map[string]bool // "list" | "find" | "create" | "update" | "delete"
	customActions          []spec.Action
}

func generateTypeScript(reg *entity.Registry) (string, error) {
	routes := append(api.GenerateRoutes(reg), api.GenerateCustomActionRoutes(reg)...)
	if len(routes) == 0 {
		return "", fmt.Errorf("no exposed entities found — nothing to generate (every Document defaults to unexposed; see spec.expose, docs/spec/02-core-basic.md §16 D49)")
	}

	groups := map[string]*entityGroup{}
	var order []string
	for _, rd := range routes {
		key := rd.Module + "." + rd.Entity
		g, ok := groups[key]
		if !ok {
			specInfo, found := reg.GetEntity(rd.Module, rd.Entity)
			if !found || specInfo.EntitySpec == nil {
				continue
			}
			g = &entityGroup{
				module:          rd.Module,
				entity:          rd.Entity,
				plural:          rd.Plural,
				spec:            specInfo.EntitySpec,
				standardActions: map[string]bool{},
			}
			groups[key] = g
			order = append(order, key)
		}
		if rd.Handler == "auto" {
			g.standardActions[rd.Action] = true
		} else {
			for _, a := range g.spec.Actions {
				if a.Name == rd.Action {
					g.customActions = append(g.customActions, a)
					break
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by `forma generate`. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: forma generate --spec <dir> --out <this file>\n")
	b.WriteString("// Runtime (auth, HTTP, error mapping) lives in @forma/client — this file only\n")
	b.WriteString("// adds types and a thin typed wrapper per entity (docs/spec/05-frontend.md §7).\n\n")
	b.WriteString("import { FormaClient, FormaRecord, ListOptions, ListResult } from \"@forma/client\";\n\n")

	for _, key := range order {
		g := groups[key]
		writeEntityTypes(&b, g)
	}

	b.WriteString("export function createApi(client: FormaClient) {\n")
	b.WriteString("  return {\n")
	byModule := map[string][]string{}
	var moduleOrder []string
	for _, key := range order {
		g := groups[key]
		if _, ok := byModule[g.module]; !ok {
			moduleOrder = append(moduleOrder, g.module)
		}
		byModule[g.module] = append(byModule[g.module], key)
	}
	for _, module := range moduleOrder {
		fmt.Fprintf(&b, "    %s: {\n", tsIdent(module))
		for _, key := range byModule[module] {
			writeEntityApi(&b, groups[key])
		}
		b.WriteString("    },\n")
	}
	b.WriteString("  };\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// writeEntityTypes emits: the entity's own-fields interface, Create/Update
// input types, and one params interface per custom action.
func writeEntityTypes(b *strings.Builder, g *entityGroup) {
	typeName := pascalCase(g.module) + pascalCase(g.entity)

	fmt.Fprintf(b, "// %s.%s — table %q\n", g.module, g.entity, g.plural)
	fmt.Fprintf(b, "export interface %s {\n", typeName)
	for _, f := range g.spec.Fields {
		writeField(b, f, false)
	}
	b.WriteString("}\n\n")

	if g.standardActions["create"] {
		fmt.Fprintf(b, "export interface %sCreateInput {\n", typeName)
		for _, f := range g.spec.Fields {
			if f.Computed != nil {
				continue // derived server-side — not part of create input
			}
			writeField(b, f, false)
		}
		b.WriteString("}\n\n")
	}
	if g.standardActions["update"] {
		// All fields optional — PATCH sends only what changed (§16).
		fmt.Fprintf(b, "export type %sUpdateInput = Partial<%sCreateInput>;\n\n", typeName, typeName)
	}

	for _, action := range g.customActions {
		writeActionParamsType(b, typeName, action)
	}
}

func writeActionParamsType(b *strings.Builder, entityTypeName string, action spec.Action) {
	paramsTypeName := entityTypeName + pascalCase(action.Name) + "Params"
	if action.Params == nil || len(action.Params.Validate) == 0 {
		fmt.Fprintf(b, "export type %s = Record<string, unknown>;\n\n", paramsTypeName)
		return
	}

	fmt.Fprintf(b, "export interface %s {\n", paramsTypeName)
	for _, p := range action.Params.Validate {
		required := false
		for _, r := range p.Rules {
			if r.Name == "required" {
				required = true
			}
		}
		// No type info is declared for action params today (spec.ParamValidation
		// only carries validation rules, not a data type) — `unknown` names the
		// parameter for autocomplete without asserting a type we can't verify.
		// Quoted literal key, same reasoning as writeField: this must match the
		// JSON body key the server decodes, not a camelCased rename.
		fmt.Fprintf(b, "  %q%s: unknown;\n", p.Field, optionalMark(!required))
	}
	b.WriteString("}\n\n")
}

// writeField emits one interface property. The key is the field's literal
// name, quoted — it MUST match the wire JSON key exactly (internal/db
// EntityRecord.MarshalJSON spreads Data verbatim, no case transform), so
// this deliberately does NOT go through tsIdent's camelCasing the way
// generator-invented identifiers (module/plural/action keys) do below.
func writeField(b *strings.Builder, f spec.Field, forceOptional bool) {
	optional := forceOptional || !fieldIsRequired(f)
	tsType := tsFieldType(f)
	nullable := ""
	if optional {
		nullable = " | null"
	}
	if f.Description != "" {
		fmt.Fprintf(b, "  /** %s */\n", strings.ReplaceAll(f.Description, "\n", " "))
	}
	fmt.Fprintf(b, "  %q%s: %s%s;\n", f.Name, optionalMark(optional), tsType, nullable)
}

// fieldIsRequired checks both ways a manifest can declare a field required:
// the top-level `required: true` key (Field.Required) and the more common
// `rules: [required, ...]` convention (internal/validation/validator.go
// checks the same rule.Name == "required" at runtime) — real manifests in
// this repo (examples/*/spec) exclusively use the latter.
func fieldIsRequired(f spec.Field) bool {
	if f.Required {
		return true
	}
	for _, r := range f.Rules {
		if r.Name == "required" {
			return true
		}
	}
	return false
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

// tsFieldType maps a Forma field type to its TypeScript representation.
// decimal maps to string, not number: money fields MUST be arbitrary
// precision (pkg/spec/entity.go FieldDecimal doc comment) and JS `number`
// cannot represent that safely. NOTE: internal/db does not yet coerce
// decimal values to a string on the wire (no dedicated marshaling exists),
// so until that lands server-side this type is aspirational, not a
// guarantee — see docs/spec/05-frontend.md client-generation notes.
func tsFieldType(f spec.Field) string {
	switch f.Type {
	case spec.FieldString, spec.FieldUUID, spec.FieldDate, spec.FieldDateTime:
		return "string"
	case spec.FieldDecimal, spec.FieldNumber:
		return "string"
	case spec.FieldInteger:
		return "number"
	case spec.FieldBoolean:
		return "boolean"
	case spec.FieldEnum:
		if len(f.EnumValues) == 0 {
			return "string"
		}
		quoted := make([]string, len(f.EnumValues))
		for i, v := range f.EnumValues {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		return strings.Join(quoted, " | ")
	case spec.FieldJSON:
		return "unknown"
	case spec.FieldRelation:
		// A relation field on the entity itself is the referenced ID
		// (belongs_to); has_many/has_one are not modeled as record fields.
		return "string"
	case spec.FieldChild:
		if f.Child == nil || len(f.Child.Fields) == 0 {
			return "unknown[]"
		}
		var inline strings.Builder
		inline.WriteString("Array<{ ")
		for i, cf := range f.Child.Fields {
			if i > 0 {
				inline.WriteString(" ")
			}
			cfOptional := !fieldIsRequired(cf)
			opt := optionalMark(cfOptional)
			nullable := ""
			if cfOptional {
				nullable = " | null"
			}
			fmt.Fprintf(&inline, "%q%s: %s%s;", cf.Name, opt, tsFieldType(cf), nullable)
		}
		inline.WriteString(" }>")
		return inline.String()
	default:
		return "unknown"
	}
}

func writeEntityApi(b *strings.Builder, g *entityGroup) {
	typeName := pascalCase(g.module) + pascalCase(g.entity)
	fmt.Fprintf(b, "      %s: {\n", tsIdent(g.plural))

	if g.standardActions["list"] {
		fmt.Fprintf(b, "        list: (opts?: ListOptions): Promise<ListResult<FormaRecord<%s>>> =>\n", typeName)
		fmt.Fprintf(b, "          client.list<FormaRecord<%s>>(%q, %q, opts),\n", typeName, g.module, g.plural)
	}
	if g.standardActions["find"] {
		fmt.Fprintf(b, "        find: (id: string): Promise<FormaRecord<%s>> =>\n", typeName)
		fmt.Fprintf(b, "          client.find<FormaRecord<%s>>(%q, %q, id),\n", typeName, g.module, g.plural)
	}
	if g.standardActions["create"] {
		fmt.Fprintf(b, "        create: (input: %sCreateInput): Promise<FormaRecord<%s>> =>\n", typeName, typeName)
		fmt.Fprintf(b, "          client.create<FormaRecord<%s>>(%q, %q, input),\n", typeName, g.module, g.plural)
	}
	if g.standardActions["update"] {
		fmt.Fprintf(b, "        update: (id: string, patch: %sUpdateInput): Promise<FormaRecord<%s>> =>\n", typeName, typeName)
		fmt.Fprintf(b, "          client.update<FormaRecord<%s>>(%q, %q, id, patch),\n", typeName, g.module, g.plural)
	}
	if g.standardActions["delete"] {
		fmt.Fprintf(b, "        delete: (id: string): Promise<void> => client.delete(%q, %q, id),\n", g.module, g.plural)
	}
	for _, action := range g.customActions {
		paramsTypeName := typeName + pascalCase(action.Name) + "Params"
		fmt.Fprintf(b, "        %s: (id: string, params: %s): Promise<unknown> =>\n", tsIdent(action.Name), paramsTypeName)
		fmt.Fprintf(b, "          client.action(%q, %q, id, %q, params),\n", g.module, g.plural, action.Name)
	}

	b.WriteString("      },\n")
}

// pascalCase converts kebab/snake_case names (module and entity names) into
// a TypeScript-identifier-safe PascalCase segment, e.g. "general-ledger" ->
// "GeneralLedger".
func pascalCase(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '-' || r == '_' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// tsIdent converts a snake_case/kebab-case name into a camelCase property
// name safe to use unquoted as a TS object key.
func tsIdent(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '-' || r == '_' })
	if len(parts) == 0 {
		return name
	}
	var b strings.Builder
	b.WriteString(parts[0])
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}
