// Command `forma generate ruby-app` scaffolds a Ruby sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGenerateRubyApp(args []string) {
	fs := flag.NewFlagSet("generate ruby-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate ruby-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a Ruby sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	files := map[string]string{
		"Gemfile":        scaffoldRubyGemfile(),
		"app.rb":         scaffoldRubyApp(mod, ent, act),
		"forma-app.yaml": scaffoldRubyAppYAML(),
		".gitignore":     scaffoldRubyGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Ruby sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  bundle install\n")
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldRubyGemfile() string {
	return `# frozen_string_literal: true

source "https://rubygems.org"

gem "lib-forma", path: "../../sdk/ruby"
`
}

func scaffoldRubyApp(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return fmt.Sprintf(`# frozen_string_literal: true

# Forma Ruby sidecar app — generated by `+"`forma generate ruby-app`"+`.
#
# Registers business-logic handlers and starts the App listener.

require "lib-forma"

app = Forma::App.new

app.handle("%s") do |inv, ctx|
  $stderr.puts "[%s] invoked: resource_id=#{inv.resource_id}"

  # Return action result with optional state transition.
  Forma::ActionResult.new(
    { processed: true, at: Time.now.iso8601 },
    new_state: "processed"
  )
end

app.run
`, handlerID, handlerID)
}

func scaffoldRubyAppYAML() string {
	return `# ── Forma App Config — Ruby Sidecar App ──
#
# Generated by ` + "`forma generate ruby-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: ruby
app-dir: app
app-entrypoint: app.rb
dev: true
`
}

func scaffoldRubyGitignore() string {
	return `vendor/bundle/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
