// Command `forma generate php-app` scaffolds a PHP sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGeneratePHPApp(args []string) {
	fs := flag.NewFlagSet("generate php-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate php-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a PHP sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	files := map[string]string{
		"composer.json":      scaffoldPHPComposer(),
		"app.php":            scaffoldPHPApp(mod, ent, act),
		"forma-sidecar.yaml": scaffoldPHPSidecarYAML(),
		".gitignore":         scaffoldPHPGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded PHP sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  composer install\n")
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldPHPComposer() string {
	return `{
    "name": "myapp/forma-sidecar",
    "description": "Forma PHP sidecar app",
    "type": "project",
    "require": {
        "php": ">=8.1",
        "forma/lib-forma": "@dev"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "repositories": [
        {
            "type": "path",
            "url": "../../sdk/php"
        }
    ]
}
`
}

func scaffoldPHPApp(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return fmt.Sprintf(`<?php
/**
 * Forma PHP sidecar app — generated by `+"`forma generate php-app`"+`.
 *
 * Registers business-logic handlers and starts the App listener.
 */

require __DIR__ . '/vendor/autoload.php';

use Forma\App;
use Forma\ActionResult;

$app = new App();

$app->handle('%s', function ($inv, $ctx) {
    fwrite(STDERR, "[%s] invoked: resource_id=" . $inv->resourceId . "\n");
    return new ActionResult(
        ['processed' => true, 'at' => date(DATE_ATOM)],
        'processed'
    );
});

$app->run();
`, handlerID, handlerID)
}

func scaffoldPHPSidecarYAML() string {
	return `# ── Forma Dev Config — PHP Sidecar App ──
#
# Generated by ` + "`forma generate php-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: php
app-dir: app
app-entrypoint: app.php
listen: unix_socket
app-endpoint: unix_socket
listen-url: unix:///tmp/forma-sidecar.sock
app-endpoint-url: unix:///tmp/forma-app.sock
dev: true
`
}

func scaffoldPHPGitignore() string {
	return `vendor/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
