// Command `forma generate java-app` scaffolds a Java sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGenerateJavaApp(args []string) {
	fs := flag.NewFlagSet("generate java-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate java-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a Java sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	dirs := []string{
		filepath.Join(absDir, "src", "main", "java"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create %s: %v\n", d, err)
			os.Exit(1)
		}
	}

	files := map[string]string{
		"pom.xml": scaffoldJavaPom(),
		filepath.Join("src", "main", "java", "App.java"): scaffoldJavaApp(mod, ent, act),
		"forma-app.yaml": scaffoldJavaAppYAML(),
		".gitignore":     scaffoldJavaGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Java sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldJavaPom() string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.forma</groupId>
    <artifactId>my-forma-app</artifactId>
    <version>0.1.0</version>
    <packaging>jar</packaging>

    <name>my-forma-app</name>
    <description>Forma Java sidecar app</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.forma</groupId>
            <artifactId>lib-forma</artifactId>
            <version>0.1.0</version>
            <scope>system</scope>
            <systemPath>${basedir}/../../sdk/java/target/lib-forma-0.1.0.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`
}

func scaffoldJavaApp(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return fmt.Sprintf(`import io.forma.*;
import java.time.Instant;
import java.util.Map;

/**
 * Forma Java sidecar app — generated by `+"`forma generate java-app`"+`.
 */
public class App {

    public static void main(String[] args) {
        try (var app = new App()) {

            app.handle("%s", (Invocation inv, Ctx ctx) -> {
                System.err.println("[%s] invoked: resource_id=" + inv.resourceId());
                return new ActionResult(
                    Map.of("processed", true, "at", Instant.now().toString()),
                    "processed"
                );
            });

            app.run();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
}
`, handlerID, handlerID)
}

func scaffoldJavaAppYAML() string {
	return `# ── Forma App Config — Java Sidecar App ──
#
# Generated by ` + "`forma generate java-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: java
app-dir: app
app-entrypoint: App.java
dev: true
`
}

func scaffoldJavaGitignore() string {
	return `target/
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
*.class
`
}
