// Command `forma generate python-app` scaffolds a Python sidecar app.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runGeneratePythonApp(args []string) {
	fs := flag.NewFlagSet("generate python-app", flag.ExitOnError)
	dir := fs.String("dir", "./app", "Target directory for the scaffolded app")
	moduleName := fs.String("module", "myapp", "Module name for the example handler")
	entityName := fs.String("entity", "myentity", "Entity name for the example handler")
	actionName := fs.String("action", "process", "Action name for the example handler")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: forma generate python-app [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Scaffold a Python sidecar app for a Forma project.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
	}
	fs.Parse(args)

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if _, err := os.Stat(absDir); err == nil {
		fmt.Fprintf(os.Stderr, "Error: target %s already exists\n", absDir)
		os.Exit(1)
	}

	mod := strings.ToLower(*moduleName)
	ent := strings.ToLower(*entityName)
	act := strings.ToLower(*actionName)

	files := map[string]string{
		"pyproject.toml":                scaffoldPythonPyproject(),
		"app.py":                        scaffoldPythonApp(ent, act),
		filepath.Join("src", act+".py"): scaffoldPythonHandler(mod, ent, act),
		"forma-app.yaml":                scaffoldPythonAppYAML(),
		".gitignore":                    scaffoldPythonGitignore(),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(absDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: create dir for %s: %v\n", relPath, err)
			os.Exit(1)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: write %s: %v\n", fullPath, err)
			os.Exit(1)
		}
	}

	fmt.Printf("✅ Scaffolded Python sidecar app in %s\n\n", absDir)
	fmt.Printf("Next steps:\n")
	fmt.Printf("  cd %s\n", absDir)
	fmt.Printf("  pip install -e .\n")
	fmt.Printf("  cd .. && forma dev\n")
}

func scaffoldPythonPyproject() string {
	return `[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "my-forma-app"
version = "0.1.0"
description = "Forma Python sidecar app"
requires-python = ">=3.9"
dependencies = [
    "lib-forma @ file:///${PROJECT_ROOT}/../../sdk/python",
]
`
}

func scaffoldPythonApp(entity, action string) string {
	return fmt.Sprintf(`"""
Forma Python sidecar app — generated by `+"`forma generate python-app`"+`.

Registers business-logic handlers and starts the App listener.
"""
import sys
import os

# Ensure the SDK is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../sdk/python"))

from lib_forma import App
from src.%s import register_%s_%s_handler

app = App()
register_%s_%s_handler(app)

if __name__ == "__main__":
    app.run()
`, action, entity, action, entity, action)
}

func scaffoldPythonHandler(module, entity, action string) string {
	handlerID := fmt.Sprintf("%s.%s.%s", module, entity, action)
	return fmt.Sprintf(`"""
%s handler — example sidecar action.
"""
from lib_forma import ActionResult, App


def register_%s_%s_handler(app: App):
    @app.action("%s")
    def handler(inv, ctx):
        print("[%s] invoked: resource_id=%%s" %% inv.resource_id, file=__import__("sys").stderr)
        return ActionResult(
            {"processed": True, "at": __import__("datetime").datetime.now().isoformat()},
            "processed",
        )
`, handlerID, entity, action, handlerID, handlerID)
}

func scaffoldPythonAppYAML() string {
	return `# ── Forma App Config — Python Sidecar App ──
#
# Generated by ` + "`forma generate python-app`" + `.

spec: spec
dsn: sqlite:.forma/data.db
runtime: python
app-dir: app
app-entrypoint: app.py
dev: true
`
}

func scaffoldPythonGitignore() string {
	return `.venv/
__pycache__/
*.pyc
.forma/
*.db
*.db-shm
*.db-wal
/tmp/forma-*.sock
`
}
