package db

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/primadi/formspec/pkg/spec"
)

// newEntryModeStore builds a store for one entity whose natural key uses the
// given entry mode. `rule` is nil for the pure user-entry case.
func newEntryModeStore(t *testing.T, dbName string, entry spec.NaturalKeyEntry, rule *spec.NaturalKeyRuleDecl) *EntityStore {
	t.Helper()
	dir := t.TempDir()
	d, err := OpenSQLite(filepath.Join(dir, dbName), nil)
	if err != nil {
		t.Fatalf("OpenSQLite: %v", err)
	}
	t.Cleanup(func() { _ = d.Close() })

	meta := spec.Metadata{Name: "invoice", Module: "billing"}
	entity := &spec.EntitySpec{
		Version: "v1",
		Fields: []spec.Field{
			{
				Name:            "number",
				Type:            spec.FieldString,
				NaturalKey:      true,
				NaturalKeyRule:  rule,
				NaturalKeyEntry: entry,
			},
			{Name: "note", Type: spec.FieldString},
		},
	}
	if err := spec.ValidateEntitySpec(entity); err != nil {
		t.Fatalf("ValidateEntitySpec: %v", err)
	}

	r := NewMigrationRunner(d, DriverSQLite)
	if _, err := r.ApplyMigrations(context.Background(), []EntityMigration{{Metadata: meta, EntitySpec: *entity}}); err != nil {
		t.Fatalf("ApplyMigrations: %v", err)
	}
	return NewEntityStore(d, DriverSQLite, meta, entity)
}

var seqRule = &spec.NaturalKeyRuleDecl{Strategy: "sequence", Format: "INV-{seq:05d}"}

// TestNaturalKeyEntry_AutoGeneratedIgnoresUserValue pins the difference between
// the two minting modes. `auto_generated` means the key is NOT an input: a
// supplied value is dropped rather than honoured, because accepting it would let
// a caller pin a number the sequence later hands to somebody else.
func TestNaturalKeyEntry_AutoGeneratedIgnoresUserValue(t *testing.T) {
	store := newEntryModeStore(t, "entry_auto.db", spec.NaturalKeyEntryAutoGenerated, seqRule)
	ctx := context.Background()

	id, err := store.Insert(ctx, InsertParams{
		WorkspaceID: "t1", CreatedBy: "u",
		Data: map[string]any{"number": "PAPER-001", "note": "x"},
	})
	if err != nil {
		t.Fatalf("Insert: %v", err)
	}
	rec, err := store.GetByID(ctx, GetByIDParams{WorkspaceID: "t1", ID: id})
	if err != nil {
		t.Fatalf("GetByID: %v", err)
	}
	if got := rec.Data["number"]; got == "PAPER-001" {
		t.Error("auto_generated must IGNORE a caller-supplied value, got the supplied one")
	} else if got != "INV-00001" {
		t.Errorf("expected the minted key INV-00001, got %v", got)
	}
}

// TestNaturalKeyEntry_AutoGeneratedIfEmptyHonoursUserValue pins the historical
// `strategy: sequence` behaviour that `order.number` and
// `purchase-order.number` depend on: a supplied value wins, the engine mints
// only when nothing was supplied.
func TestNaturalKeyEntry_AutoGeneratedIfEmptyHonoursUserValue(t *testing.T) {
	store := newEntryModeStore(t, "entry_if_empty.db", spec.NaturalKeyEntryAutoGeneratedIfEmpty, seqRule)
	ctx := context.Background()

	overrideID, err := store.Insert(ctx, InsertParams{
		WorkspaceID: "t1", CreatedBy: "u",
		Data: map[string]any{"number": "PAPER-001", "note": "override"},
	})
	if err != nil {
		t.Fatalf("Insert (override): %v", err)
	}
	rec, err := store.GetByID(ctx, GetByIDParams{WorkspaceID: "t1", ID: overrideID})
	if err != nil {
		t.Fatalf("GetByID: %v", err)
	}
	if rec.Data["number"] != "PAPER-001" {
		t.Errorf("auto_generated_if_empty must honour the supplied value, got %v", rec.Data["number"])
	}

	// And it still mints when the value is absent.
	mintedID, err := store.Insert(ctx, InsertParams{
		WorkspaceID: "t1", CreatedBy: "u",
		Data: map[string]any{"note": "no number"},
	})
	if err != nil {
		t.Fatalf("Insert (mint): %v", err)
	}
	minted, err := store.GetByID(ctx, GetByIDParams{WorkspaceID: "t1", ID: mintedID})
	if err != nil {
		t.Fatalf("GetByID: %v", err)
	}
	if minted.Data["number"] == nil || minted.Data["number"] == "" {
		t.Errorf("expected a minted key for an absent value, got %v", minted.Data["number"])
	}
}

// TestNaturalKeyEntry_UserEntryNeverMints pins the mode whose whole point is
// that a person, a seed, or a hook supplies the value: the engine must not
// invent one, even when a rule exists for its shape.
func TestNaturalKeyEntry_UserEntryNeverMints(t *testing.T) {
	store := newEntryModeStore(t, "entry_user.db", spec.NaturalKeyEntryUserEntry, seqRule)
	ctx := context.Background()

	id, err := store.Insert(ctx, InsertParams{
		WorkspaceID: "t1", CreatedBy: "u",
		Data: map[string]any{"number": "ACC-100", "note": "supplied"},
	})
	if err != nil {
		t.Fatalf("Insert: %v", err)
	}
	rec, err := store.GetByID(ctx, GetByIDParams{WorkspaceID: "t1", ID: id})
	if err != nil {
		t.Fatalf("GetByID: %v", err)
	}
	if rec.Data["number"] != "ACC-100" {
		t.Errorf("user_entry must keep the supplied value, got %v", rec.Data["number"])
	}
}

// TestResolveNaturalKeyEntry_Convention pins the backward-compatibility rule:
// every declaration written before `natural_key_entry` existed must keep its
// meaning, so absence resolves by convention rather than erroring.
func TestResolveNaturalKeyEntry_Convention(t *testing.T) {
	cases := []struct {
		name  string
		field spec.Field
		want  spec.NaturalKeyEntry
	}{
		{"no rule → user", spec.Field{NaturalKey: true}, spec.NaturalKeyEntryUserEntry},
		{"sequence → auto if empty", spec.Field{NaturalKey: true, NaturalKeyRule: &spec.NaturalKeyRuleDecl{Strategy: "sequence"}}, spec.NaturalKeyEntryAutoGeneratedIfEmpty},
		{"custom → user", spec.Field{NaturalKey: true, NaturalKeyRule: &spec.NaturalKeyRuleDecl{Strategy: "custom"}}, spec.NaturalKeyEntryUserEntry},
		{"declared wins", spec.Field{NaturalKey: true, NaturalKeyEntry: spec.NaturalKeyEntryAutoGenerated, NaturalKeyRule: &spec.NaturalKeyRuleDecl{Strategy: "sequence"}}, spec.NaturalKeyEntryAutoGenerated},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := spec.ResolveNaturalKeyEntry(&tc.field); got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// TestValidateEntitySpec_AutoGeneratedNeedsRule pins the one contradiction worth
// refusing: "the engine is the only author" with nothing to generate with.
func TestValidateEntitySpec_AutoGeneratedNeedsRule(t *testing.T) {
	entity := &spec.EntitySpec{Fields: []spec.Field{
		{Name: "code", Type: spec.FieldString, NaturalKey: true, NaturalKeyEntry: spec.NaturalKeyEntryAutoGenerated},
	}}
	if err := spec.ValidateEntitySpec(entity); err == nil {
		t.Fatal("auto_generated without a natural_key_rule must be refused")
	}
}
