apiVersion: forma.dev/v1alpha1
kind: Form
metadata:
  name: customer-create
  module: crc
  description: Form buat pelanggan baru
spec:
  entity: customer
  mode: create
  render: drawer
  sections:
    - title: "Informasi Perusahaan"
      fields:
        - { field: code }
        - { field: name }
        - { field: address }
        - { field: phone }
        - { field: email }
    - title: "Informasi Tambahan"
      fields:
        - { field: npwp }
        - { field: contact_person }
        - { field: is_active }
        - { field: notes }
