apiVersion: formspec.dev/v1
kind: Config
metadata:
  name: app
  module: core
  description: App-level config untuk General Ledger
spec:
  keys:
    workspace_name:
      type: string
      default: "default"
